import assert from "node:assert/strict";

import {
  evaluateLeagueBehaviourV01,
  LEAGUE_BEHAVIOUR_MODEL_VERSION_V01,
} from "../src/lib/predictions/league-behaviour-v0.1";

function main() {
  /*
   * Egypt + D=+1
   */
  const egyptPlusOne =
    evaluateLeagueBehaviourV01({
      country:
        "Egypt",

      competitionName:
        "Premier League",

      ratingGap:
        1,
    });

  assert.equal(
    egyptPlusOne.profile,
    "egypt_micro_gap",
  );

  assert.equal(
    egyptPlusOne.resultSignal,
    "draw_support",
  );

  assert.equal(
    egyptPlusOne.goalsSignal,
    "under_2_5_support",
  );

  /*
   * Egypt + D=-4
   */
  const egyptMinusFour =
    evaluateLeagueBehaviourV01({
      country:
        "Egypt",

      competitionName:
        "Second League",

      ratingGap:
        -4,
    });

  assert.equal(
    egyptMinusFour.profile,
    "egypt_micro_gap",
  );

  assert.equal(
    egyptMinusFour.absoluteGap,
    4,
  );

  assert.equal(
    egyptMinusFour.resultSignal,
    "draw_support",
  );

  assert.equal(
    egyptMinusFour.goalsSignal,
    "under_2_5_support",
  );

  /*
   * Egypt zero-gap:
   *
   * The global result model can still regard
   * zero as draw territory, but this specific
   * league prior is defined only for 1-4.
   */
  const egyptZero =
    evaluateLeagueBehaviourV01({
      country:
        "Egypt",

      competitionName:
        "Premier League",

      ratingGap:
        0,
    });

  assert.equal(
    egyptZero.profile,
    "neutral",
  );

  assert.equal(
    egyptZero.resultSignal,
    "none",
  );

  /*
   * Egypt outside micro-gap.
   */
  const egyptFive =
    evaluateLeagueBehaviourV01({
      country:
        "Egypt",

      competitionName:
        "Premier League",

      ratingGap:
        5,
    });

  assert.equal(
    egyptFive.profile,
    "neutral",
  );

  /*
   * Slovenia:
   * always classified as swing for now.
   */
  const slovenia =
    evaluateLeagueBehaviourV01({
      country:
        "Slovenia",

      competitionName:
        "PrvaLiga",

      ratingGap:
        3,
    });

  assert.equal(
    slovenia.profile,
    "swing_league",
  );

  assert.equal(
    slovenia.gapReliability,
    "reduced",
  );

  assert.equal(
    slovenia.resultSignal,
    "none",
  );

  /*
   * Large gaps remain swing-classified too.
   * This does NOT reverse the rating signal;
   * it only reduces standalone reliance.
   */
  const sloveniaLarge =
    evaluateLeagueBehaviourV01({
      country:
        "Slovenia",

      competitionName:
        "PrvaLiga",

      ratingGap:
        175,
    });

  assert.equal(
    sloveniaLarge.profile,
    "swing_league",
  );

  assert.equal(
    sloveniaLarge.gapReliability,
    "reduced",
  );

  /*
   * Slovakia.
   */
  const slovakia =
    evaluateLeagueBehaviourV01({
      country:
        "Slovakia",

      competitionName:
        "Super Liga",

      ratingGap:
        -27,
    });

  assert.equal(
    slovakia.profile,
    "swing_league",
  );

  assert.equal(
    slovakia.gapReliability,
    "reduced",
  );

  /*
   * Other countries remain neutral.
   */
  const england =
    evaluateLeagueBehaviourV01({
      country:
        "England",

      competitionName:
        "Premier League",

      ratingGap:
        2,
    });

  assert.equal(
    england.profile,
    "neutral",
  );

  assert.equal(
    england.gapReliability,
    "normal",
  );

  assert.equal(
    england.resultSignal,
    "none",
  );

  assert.equal(
    england.goalsSignal,
    "none",
  );

  /*
   * Missing country does not fabricate
   * league behaviour.
   */
  const unknown =
    evaluateLeagueBehaviourV01({
      country:
        null,

      competitionName:
        null,

      ratingGap:
        2,
    });

  assert.equal(
    unknown.profile,
    "neutral",
  );

  /*
   * No probability or recommendation is ever
   * generated by this layer.
   */
  const outputs = [
    egyptPlusOne,
    egyptMinusFour,
    egyptZero,
    egyptFive,
    slovenia,
    sloveniaLarge,
    slovakia,
    england,
    unknown,
  ];

  for (
    const output
    of outputs
  ) {
    assert.equal(
      output.modelVersion,
      LEAGUE_BEHAVIOUR_MODEL_VERSION_V01,
    );

    assert.equal(
      output.calibratedProbability,
      null,
    );

    assert.equal(
      output.recommendationStatus,
      "not_evaluated",
    );

    assert.equal(
      output.bttsSignal,
      "none",
    );
  }

  console.log(
    `PASS: ${LEAGUE_BEHAVIOUR_MODEL_VERSION_V01}`,
  );

  console.log(
    "PASS: Egypt 1-4 micro-gap produces Draw support.",
  );

  console.log(
    "PASS: Egypt 1-4 micro-gap produces Under 2.5 support.",
  );

  console.log(
    "PASS: Egypt zero-gap is not silently added to the league-specific 1-4 rule.",
  );

  console.log(
    "PASS: Slovenia is classified as a swing league.",
  );

  console.log(
    "PASS: Slovakia is classified as a swing league.",
  );

  console.log(
    "PASS: swing classification reduces rating-gap reliability without reversing the forecast.",
  );

  console.log(
    "PASS: unstudied leagues remain neutral.",
  );

  console.log(
    "PASS: league behaviour never fabricates probabilities.",
  );

  console.log(
    "PASS: league behaviour does not automatically create betting recommendations.",
  );
}

main();